import { Montserrat } from "next/font/google";
import "./globals.css";



const getMontserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Co-Criativo | Loja Colaborativa",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/logoSimbolo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={` ${getMontserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
